title: Javier Castillo
description: Dockeando es una recopilaci√≥n los mejores proyectos que tengo en mi red local en Docker.
theme: just-the-docs

aux_links:
  "Mi GitHub": "https://github.com/javiercast0"

favicon_ico: "/assets/images/favicon.ico"
search_enabled: false
aux_links_new_tab: true
color_scheme: light